# Generated by Django 5.2.5 on 2025-09-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='entrenador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='pais',
            field=models.CharField(max_length=50),
        ),
    ]
